### ISSUE TITLE
[HS2]StudioWindowResize Outfit list overflowing

### ISSUE THREAD

**Issue by BullOnMars** [DeathWeasel1337/KK_Plugins#141] opened 2022-04-29 06:32 UTC
Title, in studio, the outfit list is overflowing in HS2, other games not tested.
Plus UI incompatibility with Browser Folders 2.6.2, list is overlapping with Browser Folders UI, since Browser Folders UI cannot be moved.

**Comment by ManlyMarco** [comment] 2022-05-30 17:58
Confirmed.
Overflowing is caused by [this](https://github.com/IllusionMods/KK_Plugins/blob/master/src/StudioWindowResize.Core/StudioWindowResizePlugin.cs#L119) line. Character lists need to be checked as well, might need to change over to the Strict version of the method.
Overlapping with Browser Folders is known, it needs to be fixed on the Browser Folders side by letting the windows be resized.

**Closed as completed** 2022-08-22 18:40 UTC
Labels: bug
