### ISSUE TITLE
UncensorSelector Koikatu GenderBend Penis problem

### ISSUE THREAD

**Issue by Hyp0cri5y** [DeathWeasel1337/KK_Plugins#69] opened 2021-02-04 12:37 UTC
Hi,

i tried to use the Genderbend option of uncensorselector and created a futa char. If i use Free H the girl has a dick but if i play normal its not showing. I dont know if its a uncensorselector problem or a game issue. I tried diffrent settings but it wont work.

**Comment by HoyDog** [comment] 2021-02-16 06:13
also having this issue, havent found a fix

**Comment by DeathWeasel1337** [comment] 2021-02-28 21:25
Having trouble replicating this issue. In main game H mode and in dialogues the penis shows properly for me. The only place it does not show is in the school free roaming mod, and this is because low poly models don't have penises at all. Using ForceHighPoly causes them to show normall in this mode as well. Can you describe the problem a bit more so I can try to fix it?

**Comment by Hyp0cri5y** [comment] 2021-03-03 17:56
Hey, thanks for the reply. 

I create a char and choose one of the penis from the dropdown. If i now choose the char in Free H everything working fine. If i start the "story" and walk to the char and choose "Do H" no penis is appearing. Its with every char i try with a penis.

**Comment by DeathWeasel1337** [comment] 2021-03-03 19:54
Works on my box, not sure what the problem could be. This is the version I'm using, built from the latest code. Give it a try and see if that fixes the problem. I have a bad habit of finding a bug, fixing it, then forgetting all about.
[KK_UncensorSelector v3.11.1.zip](https://github.com/DeathWeasel1337/KK_Plugins/files/6078774/KK_UncensorSelector.v3.11.1.zip)

**Comment by Hyp0cri5y** [comment] 2021-03-05 07:35
Didn't helped. Nedded to update bepis and kkapi too. I think its my game at this point. The first time i loaded my save with 2 Futa girls my game crashed immediately after loading the free roaming with some weird error messages i never had. Before that it worked like 1 time only. I redownload the whole game and test again

**Comment by Hyp0cri5y** [comment] 2021-03-05 08:52
Same problem with new game download and a new char. No penis in story mode sex scenes

**Comment by DeathWeasel1337** [comment] 2021-03-05 19:49
Really not sure what could be causing this. It could be some conflict with another plugin, you could upload your BepInEx folder and I could try it with your plugin setup to see if it misbehaves for me.

**Comment by Hyp0cri5y** [comment] 2021-03-05 20:24
https://www.file-upload.net/download-14511149/BepInEx.7z.html

Here is the BepInEx folder. Its from the ScrewThisNoise RX8 Pack

**Comment by DeathWeasel1337** [comment] 2021-03-05 22:14
Tried out your plugin setup and I can reproduce the issue. Pulled out plugins until it stopped happening and narrowed it down to the SkinEffects plugin.  Disabling the "Persist clothes state in school" setting of SkinEffects also fixes the issue. I'll coordinate with Marco and see about getting this fixed.

**Comment by Hyp0cri5y** [comment] 2021-03-06 12:08
Its working. Thanks for the help!

**Comment by DeathWeasel1337** [comment] 2021-03-22 18:16
Talked with Marco about it and it will be fixed in the next update of SkinEffects, assuming it hasn't been released already

**Closed by DeathWeasel1337** 2021-03-22 18:16 UTC
